### ISSUE TITLE
Interpretation of the output "train_cluster_inverse" (MRF)

### ISSUE THREAD

**Issue by pstammer** [snap-stanford/casc#1]
Hi!

Im currently studying in Aachen, Germany and came around your Code on a Project. However i have an issue interpreting the outputs of the CASCSolver.PerformFullCASC function. I want to study the correlation of the different input variables of a timeseries data set and im having trouble understanding what values exactly should be expected from the output MRF and therefor dont know how to analyze the results.
For example i dont know how to deal with negative returned values in the MRF-matrix. Do they suggest a negative proportionality or should all the values of the MRF just be normalized e.g. to values between 0 and 1?
I read your paper on the CASC algorithm and try'd to work my way through the code to find an answer, but didn't get lucky till now.

I hope you can help me with my problems.

Greetings from Germany

p.s. please excuse my bad English

**Comment by scoutsaachi** [comment]
Hi!

The MRFs matrix are the inverse covariance matrices for each state. Essentially, each state is parameterized by an inverse covariance matrix (\Theta in the paper).  The state model is based off of TICC (see https://arxiv.org/pdf/1706.03161.pdf). Since our TICC window size is 1, if there are n sensors and k states, we receive k nxn matrices each of which represent the relationships between sensors for each state (the state assignment is the first value returned by the solver). This inverse covariance matrix can also be thought of as the adjacency matrix of the state's MRF. 

Inverse covariance matrices are also called precision matrices and can be used to calculate the conditional dependence of variables: Theta_{ij} is 0 if sensors i and j are independent conditioned on all the other sensors. Negative values are fine, because it's possible that two sensor values are negatively correlated.

Some helpful references:
TICC: https://arxiv.org/pdf/1706.03161.pdf
TVGL (which uses the same type of model): http://stanford.edu/~boyd/papers/pdf/tvgl.pdf
Precision Matrices and Partial Correlations: 
https://en.wikipedia.org/wiki/Precision_(statistics)
https://en.wikipedia.org/wiki/Partial_correlation#Using_matrix_inversion

Let me know if that answers your question.

**Comment by pstammer** [comment]
Hi,

First of all thank you for your quick answer! This already helps a lot. I've got a follow-up question though. In the results of the MRF matricies i frequently have values on the matrix-diagonal which are unequal to 1 what irritates me cause to my understanding the adjacency of a sensor to itself should always be 1.
Is there a fault in this assumption or can you help me understand what i am missing?
For context, i am currently trying to cluster timeseries data of energy systems in buildings, such as temperatures, volume flows or activation states of the devices.

**Comment by scoutsaachi** [comment]
The diagonal elements are related to the variance of those variables.

**Comment by pstammer** [comment]
Hello again,

I wanted to politely ask if I am allowed to use the "Figure 1" image on the MASA paper as well as the "Figure 1" image of the TICC paper in my student thesis. I think these images visualize the principle of the algorithms very well and I therefore would like to include them in my thesis to support the understanding of the algorithms. Of course I would give full credit of the images to you, the authors, on the images, by stating that they are from your paper which I of course will also cite.

Sincerely

Pascal Stammer

**Comment by scoutsaachi** [comment]
Of course! Please cite the version at https://milets19.github.io/papers/milets19_paper_3.pdf

**Comment by AB-cyber** [comment]
Dear Sir,

I am trying to run the given code untitled 'cycling.py" unfortunately I have this error : 
cannot import name 'TICCSolver' from 'TICC_solver' . Consequently I think you missed this file in your github. Could you please confirm this issue.

Regards.

**Comment by roks** [comment]
TICC is available here: https://github.com/davidhallac/TICC

**Comment by AB-cyber** [comment]
First of all, Tank you for your quick answer. 

Yes of course I downloaded and used this version of TICC implementation. Unfortunately in your code line 63
your are using:  solver.PerformFullTICC    (cluster_assignment, cluster_MRFs, motifs, motifRanked, bic, _) = solver.PerformFullTICC(
        initialClusteredPoints=old_assign, useMotif=usemotif)
But this function doesn't exist in the current TICC code that I donwloaded for github
Thanks in advance for your answer

    Le mardi 7 janvier 2020 à 23:52:38 UTC+1, roks <notifications@github.com> a écrit :  
 
 
TICC is available here: https://github.com/davidhallac/TICC

**Comment by arpnomic** [comment]
The Cluster _MRFs contain no 'zero' values (although many of the values are significantly small <<0.01). Why is that the case and can they be treated as 0?
